Fix typos in docs
plotly/Plotly.NET pull request #410
Opened 2023-08-07 21:22 UTC by chausner

This fixes various typos and tweaks punctation/grammar in the documentation.

2023-08-10 06:24 UTC, kMutagene requested changes
Thanks for this thorough check. I think there is a an unintentional file duplication, otherwise LGTM!

2023-08-10 06:24 UTC, kMutagene commented on docs/finance-charts/defaults.fsx
I think this file ended up here by mistake, as it already exists in the `general` folder.

2023-08-10 10:43 UTC, chausner commented on docs/finance-charts/defaults.fsx
Oops, not sure how this happened. I removed the copy again.

2023-08-11 06:45 UTC, kMutagene approved these changes

2023-08-11 07:33 UTC, merged

2023-08-11 07:33 UTC, kMutagene commented
Thanks!